### PR TITLE
Add docker-compose

### PR DESCRIPTION
**Pull request by Creased**
In order to make less complex the management of Docker multi-container application (e.g., minion-backend and minion-frontend) it can be interesting to use [Docker Compose](https://docs.docker.com/compose/overview/).

### CODE REVIEW

**Comment by y0no** [comment]
Great idea! Infortunately it don't seem run on my archlinux desktop.

**Comment by Creased** [comment]
@y0no Sorry to hear that, did you follow indications on [README.md#configuring-docker](/Creased/minion-vm/blob/04aa5c7b4d4878bb477935cf8ff18dde35ebe878/README.md#configuring-docker) section?

In case you haven't already done it, you'll need to setup docker-compose on your desktop setup, please take a look at https://docs.docker.com/compose/install/.

**Comment by Creased** [comment]
Since I used `docker-compose version 1.7.0, build 0d7bf73`, I've upgraded my setup to `docker-compose version 1.9.0, build 2585387`. Even after upgrade, I'm still able to setup the Docker services.

Commands used to perform the upgrade and test:

```bash
# upgrade docker-compose
cp /usr/local/bin/docker-compose{,.low}
curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m) >/usr/local/bin/docker-compose
chmod 755 /usr/local/bin/docker-compose
docker-compose --version
# change current directory to project root
pushd /var/data/home/Creased/documents/projects/docker/minion-vm/
# replace CRLF w/ LF
perl -i -p -e 's#\r##' *
# build project services
docker-compose down
docker-compose build --no-cache
docker-compose create
docker-compose start
docker-compose ps
```

If you're still not able to setup services, can you please provide a logfile of the docker-compose output so that I'll be able to help you better.

**Comment by y0no** [comment]
Here is my process:

```
$ docker-compose -v
docker-compose version 1.9.0, build 2585387

git clone https://github.com/Creased/minion-vm.git                        
Clonage dans 'minion-vm'...
remote: Counting objects: 146, done.
remote: Total 146 (delta 0), reused 0 (delta 0), pack-reused 146
Réception d'objets: 100% (146/146), 29.47 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (81/81), fait.

$ docker-compose create
... build log ...
Starting Minion: SUCCESS
Stopping Minion: SUCCESS
 ---> 2747ce45dbec
Removing intermediate container ce1ef9ba6ae0
Step 13 : CMD service minion start && tail -F /var/log/minion/*
 ---> Running in dc44a93eb8b4
 ---> b8c7f832062c
Removing intermediate container dc44a93eb8b4
Successfully built b8c7f832062c
WARNING: Image for service minion-frontend was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating minion-backend
ERROR: Cannot create container for service minion-backend: b'network minionvm_default not found'
$ docker-compose up    
Creating network "minionvm_default" with the default driver
Creating minion-backend
Creating minion-frontend
Attaching to minion-backend, minion-frontend
minion-backend     |  * Starting database mongodb
minion-backend     |    ...done.
minion-backend     |  * Starting message broker rabbitmq-server
minion-frontend    | Starting Minion: SUCCESS
minion-frontend    | ==> /var/log/minion/minion-frontend-server.stderr.log <==
minion-frontend    |  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
minion-frontend    | 
minion-frontend    | ==> /var/log/minion/minion-frontend-server.stdout.log <==
minion-frontend    | 
minion-frontend    | ==> /var/log/minion/supervisord.log <==
minion-frontend    | 2017-01-04 10:54:49,642 INFO success: minion-frontend entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
minion-frontend    | 2017-01-04 10:54:51,486 WARN received SIGTERM indicating exit request
minion-frontend    | 2017-01-04 10:54:51,487 INFO waiting for minion-frontend to die
minion-frontend    | 2017-01-04 10:54:51,488 INFO stopped: minion-frontend (terminated by SIGTERM)
minion-frontend    | 2017-01-04 11:00:03,019 WARN Included extra file "/opt/minion/minion-frontend/etc/minion-frontend.supervisor.conf" during parsing
minion-frontend    | 2017-01-04 11:00:03,046 INFO RPC interface 'supervisor' initialized
minion-frontend    | 2017-01-04 11:00:03,046 CRIT Server 'unix_http_server' running without any HTTP authentication checking
minion-frontend    | 2017-01-04 11:00:03,047 INFO daemonizing the supervisord process
minion-frontend    | 2017-01-04 11:00:03,047 INFO supervisord started with pid 19
minion-frontend    | 2017-01-04 11:00:03,117 INFO spawned: 'minion-frontend' with pid 26
minion-frontend    | 
minion-frontend    | ==> /var/log/minion/minion-frontend-server.stderr.log <==
minion-frontend    |  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
minion-backend     |    ...done.
minion-frontend    | 
minion-frontend    | ==> /var/log/minion/supervisord.log <==
minion-frontend    | 2017-01-04 11:00:06,420 INFO success: minion-frontend entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
minion-backend     | Starting Minion: SUCCESS
minion-backend     | 2017-01-04 11:00:06,543 INFO RPC interface 'supervisor' initialized
minion-backend     | 2017-01-04 11:00:06,543 CRIT Server 'unix_http_server' running without any HTTP authentication checking
minion-backend     | 2017-01-04 11:00:06,543 INFO daemonizing the supervisord process
minion-backend     | 2017-01-04 11:00:06,544 INFO supervisord started with pid 246
minion-backend     | 2017-01-04 11:00:06,593 INFO spawnerr: can't find command 'minion-plugin-worker'
minion-backend     | 2017-01-04 11:00:06,593 INFO spawnerr: can't find command 'minion-state-worker'
minion-backend     | 2017-01-04 11:00:06,593 INFO spawnerr: can't find command 'minion-scanscheduler'
minion-backend     | 2017-01-04 11:00:06,593 INFO spawnerr: can't find command 'minion-scanschedule-worker'
minion-backend     | 2017-01-04 11:00:06,593 INFO spawnerr: can't find command 'minion-scan-worker'
minion-backend     | 2017-01-04 11:00:06,593 INFO spawnerr: can't find command 'minion-backend-api'
minion-backend     | 2017-01-04 11:00:07,599 INFO spawnerr: can't find command 'minion-plugin-worker'
minion-backend     | 2017-01-04 11:00:07,599 INFO spawnerr: can't find command 'minion-state-worker'
minion-backend     | 2017-01-04 11:00:07,599 INFO spawnerr: can't find command 'minion-scanscheduler'
minion-backend     | 2017-01-04 11:00:07,599 INFO spawnerr: can't find command 'minion-scanschedule-worker'
minion-backend     | 2017-01-04 11:00:07,600 INFO spawnerr: can't find command 'minion-scan-worker'
minion-backend     | 2017-01-04 11:00:07,600 INFO spawnerr: can't find command 'minion-backend-api'
minion-backend     | 2017-01-04 11:00:09,602 INFO spawnerr: can't find command 'minion-plugin-worker'
minion-backend     | 2017-01-04 11:00:09,602 INFO spawnerr: can't find command 'minion-state-worker'
minion-backend     | 2017-01-04 11:00:09,603 INFO spawnerr: can't find command 'minion-scanscheduler'
minion-backend     | 2017-01-04 11:00:09,603 INFO spawnerr: can't find command 'minion-scanschedule-worker'
minion-backend     | 2017-01-04 11:00:09,603 INFO spawnerr: can't find command 'minion-scan-worker'
minion-backend     | 2017-01-04 11:00:09,603 INFO spawnerr: can't find command 'minion-backend-api'
minion-backend     | 2017-01-04 11:00:12,606 INFO spawnerr: can't find command 'minion-plugin-worker'
minion-backend     | 2017-01-04 11:00:12,607 INFO gave up: minion-plugin-worker entered FATAL state, too many start retries too quickly
minion-backend     | 2017-01-04 11:00:12,607 INFO spawnerr: can't find command 'minion-state-worker'
minion-backend     | 2017-01-04 11:00:12,607 INFO gave up: minion-state-worker entered FATAL state, too many start retries too quickly
minion-backend     | 2017-01-04 11:00:12,607 INFO spawnerr: can't find command 'minion-scanscheduler'
minion-backend     | 2017-01-04 11:00:12,607 INFO gave up: minion-scanscheduler entered FATAL state, too many start retries too quickly
minion-backend     | 2017-01-04 11:00:12,607 INFO spawnerr: can't find command 'minion-scanschedule-worker'
minion-backend     | 2017-01-04 11:00:12,607 INFO gave up: minion-scanschedule-worker entered FATAL state, too many start retries too quickly
minion-backend     | 2017-01-04 11:00:12,607 INFO spawnerr: can't find command 'minion-scan-worker'
minion-backend     | 2017-01-04 11:00:12,607 INFO gave up: minion-scan-worker entered FATAL state, too many start retries too quickly
minion-backend     | 2017-01-04 11:00:12,607 INFO spawnerr: can't find command 'minion-backend-api'
minion-backend     | 2017-01-04 11:00:12,607 INFO gave up: minion-backend entered FATAL state, too many start retries too quickly
```

It seems there is error in building process

**Comment by Creased** [comment]
@y0no Yeah I've the same error, but this issue isn't tied to docker-compose, but Minion-Backend... In fact, even if you setup your services using Docker Engine, you should get the same error.

I'm already aware of this issue that need to be considered, but that's not the point of this pull-request... So, I suggest you to open another issue to allow developers to take a look at this.

**Comment by y0no** [comment]
Oh ok :)
I will open an issue related to my issue.

**Comment by Creased** [comment]
Sorry, I just noticed the network related error on the build phase of your log...

In fact, I forgot to fill-in the `networks` key on docker-compose.yml (62dfe604da7edcd18978cb618de3a1e6bf509060). Now, that should be fixed, but the last error remains...

**Comment by y0no** [comment]
Thanks!
Do you have pushed your images on docker hub or something like that ? I would like to try the compose even if the backend failed currently.

**Comment by ilyaglow** [comment]
What you guys think about moving `rabbitmq` and `mongodb` into two separate docker services?

**Pull request closed without merging**
