### PR TITLE
Updating to 16.04 and adding docker-compose.yml

### PR DESCRIPTION
**Pull request by jrm16020**
Should address some of the questions/concerns in #2 .  The compose file will stand separately from the Vagrant work.  Also updates the containers to the latest LTS release of Ubuntu.

### CODE REVIEW

**Comment by psiinon** [comment]
I'm afraid Minion is not being worked on right now, at least not at Mozilla.

**Comment by jrm16020** [comment]
@psiinon does that mean that community pull requests aren't going to get much attention?

**Comment by psiinon** [comment]
@jrm16020 I'm afraid so.

**Comment by april** [comment]
I was the last person to work on it, but I've been reassigned to different work.  If some organization wanted to take it up, I'm sure that would be appreciated.  We could also point this repo somewhere else if it was getting active development elsewhere.

**Pull request closed without merging**
